---
- name: check curl version
  shell: curl -V | sed -n '1p' | awk '{print $2}'
  register: current_curl_version
  ignore_errors: True

- name: install development packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - g++
    - make
    - binutils
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    - libcunit1-dev
    - libssl-dev
    - libxml2-dev
    - libev-dev
    - libevent-dev
    - libjansson-dev
    - libjemalloc-dev
    - cython
    - python3-dev
    - python-setuptools
  when: curl.version not in current_curl_version.stdout

- name: download nghttp2
  git: repo=https://github.com/tatsuhiro-t/nghttp2.git dest=/tmp/nghttp2
  when: curl.version not in current_curl_version.stdout

- name: build nghttp2
  action: command {{ item}} chdir=/tmp/nghttp2
  become: true
  with_items:
    - git checkout tags/v1.22.0
    - autoreconf -i
    - automake
    - autoconf
    - ./configure
    - make
    - make install
  when: curl.version not in current_curl_version.stdout

- name: install build dependencies packages
  apt: pkg={{ item }} state=build-dep update_cache=yes
  with_items:
    - curl
  when: curl.version not in current_curl_version.stdout

- name: install latest openssl dependencies packages
  apt: pkg={{ item }} default_release={{ debian.version }}-backports update_cache=yes
  with_items:
    - openssl
  when: curl.version not in current_curl_version.stdout

- name: download curl
  get_url: url="https://curl.haxx.se/download/curl-{{ curl.version }}.tar.bz2" dest="/tmp/curl.tar.bz2"
  when: curl.version not in current_curl_version.stdout

- name: extract archive
  action: command {{ item }} chdir=/tmp/
  with_items:
    - tar -xvjf curl.tar.bz2
  when: curl.version not in current_curl_version.stdout

- name: build curl
  action: command {{ item }} chdir=/tmp/curl-{{ curl.version }}
  become: true
  with_items:
    - ./configure --with-nghttp2=/usr/local --with-ssl
    - make
    - make install
    - ldconfig
  when: curl.version not in current_curl_version.stdout

- name: cleaning
  action: command {{ item }} chdir=/tmp/
  become: true
  with_items:
    - rm -rf nghttp2
    - rm curl.tar.bz2
    - rm -rf curl-{{ curl.version }}
  ignore_errors: yes
  when: curl.version not in current_curl_version.stdout
